service: serverless-fastapi

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, "dev"}
  region: eu-west-1

package:
    exclude:
        - Makefile
        - poetry.lock
        - README.md
        - tests/**
        - docs/**
        - node_modules/**
        - .virtualenv/**
        - .serverless/**
        - package.json
        - package-lock.json

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: serverless-fastapi-deps
      description: Dependencies of serverless-fastapi
      compatibleRuntimes:
        - python3.8

  customDomain:
    domainName: xmementoit.co.uk
    stage: ${self:provider.stage}
    certificateArn: arn:aws:acm:eu-west-1:398024481618:certificate/04175219-fa98-472f-8bd2-ef0198bb461c
    endpointType: "edge"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
    autoDomainWaitFor: 120

functions:
  api:
    handler: api.main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}
